name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: 🐋 Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/ruby-rails:latest
            ghcr.io/canarysplayground/ruby-rails:${{ steps.date.outputs.date }}.${{ github.run_number }}

  anchore:
    name: 🔆 Anchore Analyse
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Anchor Scan Web image
        uses: anchore/scan-action@main
        with:
          image: "ghcr.io/canarysplayground/ruby-rails:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
         
      - name: Upload Anchore Scan Report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
  
  AKS_deploy:
    name: 🚀 Deploy to AKS
    environment: 
      name: AKS Cluster
      #url: 
    runs-on: ubuntu-latest
    needs: anchore
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2   
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AKS_CREDS }}
  
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AKS_CREDS}}
        resource-group: EXL-Demo
        cluster-name: tailspin-cluster
    
    - uses: azure/k8s-create-secret@v1
      name: Create imagepullsecret for GCR
      with:
        container-registry-url: ghcr.io
        container-registry-username: ${{ github.repository_owner }}
        container-registry-password: ${{ secrets.GCR_PAT }}
        secret-name: aks-connection
        
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1
      with:       
        manifests: manifests/webdeployments.yml      
        images: ghcr.io/canarysplayground/spacegameweb:${{ steps.date.outputs.date }}.${{ github.run_number }}
        imagepullsecrets: |
          aks-connection
        force: true
