name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: 🐋 Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/canarysplayground/ruby-rails:latest
            ghcr.io/canarysplayground/ruby-rails:${{ steps.date.outputs.date }}.${{ github.run_number }}

  anchore:
    name: 🔆 Anchore Analyse
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Anchor Scan Web image
        uses: anchore/scan-action@main
        with:
          image: "ghcr.io/canarysplayground/ruby-rails:latest"
          acs-report-enable: true
          fail-build: true
          severity-cutoff: critical
         
      - name: Upload Anchore Scan Report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
