apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: ruby-test
  template:
    metadata:
      labels:
        app: ruby-test
    spec:
      containers:
      - name: ruby-test
        image: ghcr.io/canarysplayground/ruby-rails:${{ steps.date.outputs.date }}.${{ github.run_number }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ruby-test
  labels:
    app: ruby-test
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ruby-test
